[package]
name = "blake-halo2"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "blake2f-circuit",
]

[dependencies]
blake2f-circuit = { version = "^0.1.0", path = "./blake2f-circuit" }
